baseURL = "https://www.tweetsfromheaven.com"
languageCode = "en-us"
title = "Tweets From Heaven"
disqusShortname = "tweetsfromheaven"
enableRobotsTXT = true
publishDir = "docs"
date = ["date", "publishDate"]

[outputs]
    home = ["HTML"]
    page = ["HTML"]

[params]
  placeholderImage = "/img/coverArtComingSoon_300_ppi.png"
	mainLogo = "/img/TweetsFromHeaven_Logo_FullColor_ProfilePic72ppi.png"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
	  name = "series"
	  weight = 199
  [[related.indices]]
	  name = "keywords"
	  weight = 150
	[[related.indices]]
	  name  = "tags"
	  weight = 200
	[[related.indices]]
	  name  = "date"
	  weight = 1
	  pattern = "2006"
