baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
disqusShortname = "tweetsfromheaven"

date = ["date", "publishDate"]

[params]
  placeholderImage = "/img/coverArtComingSoon_300_ppi.png"

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"

[related]
  threshold = 80
  includeNewer = true
  toLower = false
  [[related.indices]]
	  name = "series"
	  weight = 199
  [[related.indices]]
	  name = "keywords"
	  weight = 150
	[[related.indices]]
	  name  = "tags"
	  weight = 200
	[[related.indices]]
	  name  = "date"
	  weight = 1
	  pattern = "2006"
